zectranet_homepage:
    path: /
    defaults: { _controller: ZectranetBundle:Index:index }

zectranet_login:
    path: /login
    defaults: { _controller: ZectranetBundle:Index:login }

zectranet_login_check:
    path: /login_check
    defaults: { _controller: ZectranetBundle:Index:loginCheck }

zectranet_logout:
    path: /logout

zectranet_user_home:
    path: /user/home
    defaults: { _controller: ZectranetBundle:User:home }

zectranet_signup:
    path: /signup
    defaults: { _controller: ZectranetBundle:Index:signup }

zectranet_signup_action:
    path: /signup_action
    defaults: { _controller: ZectranetBundle:Index:signupAct }

zectranet_forgot_password:
    path: /forgot_password
    defaults: { _controller: ZectranetBundle:Index:forgotPassword }

zectranet_reset_password:
    pattern: /reset_password/{keyForAccess}
    defaults: { _controller: ZectranetBundle:Index:resetPassword }

zectranet_reset_password_save:
    pattern: /reset_password_save/{userid}
    defaults: { _controller: ZectranetBundle:Index:resetPasswordSave }

zectranet_wde:
    path: /wde
    defaults: { _controller: ZectranetBundle:User:wde }

zectranet_user_page:
    path: /userProfile/{user_id}
    defaults: { _controller: ZectranetBundle:User:index, user_id: null }
    requirements:
            user_id: \d+

zectranet_user_settings:
    path: /user/settings
    defaults: { _controller: ZectranetBundle:User:settings }

zectranet_user_settings_general:
    path: /user/settings/general
    defaults: { _controller: ZectranetBundle:User:general }

zectranet_user_settings_email:
    path: /user/settings/email
    defaults: { _controller: ZectranetBundle:User:email }

zectranet_user_settings_site:
    path: /user/settings/site
    defaults: { _controller: ZectranetBundle:User:site }

zectranet_user_settings_changePassword:
    path: /user/settings/change_password
    defaults: { _controller: ZectranetBundle:User:changePassword }

zectranet_generate_avatar:
    path: /user/generate_avatar
    defaults: { _controller: ZectranetBundle:User:generateAvatar }

zectranet_notifications_clear:
    pattern:  /notifications/clear
    defaults: { _controller: ZectranetBundle:Notification:clearNotifications }

zectranet_notifications_show:
    pattern:  /notifications
    defaults: { _controller: ZectranetBundle:Notification:showNotifications }

zectranet_notifications_get:
    pattern:  /notifications/get
    defaults: { _controller: ZectranetBundle:Notification:getNotifications }

zectranet_show_office:
    pattern: /office/{office_id}
    defaults: { _controller: ZectranetBundle:Office:index }
    requirements:
        office_id: \d+

zectranet_add_office:
    path: /office/add
    defaults: { _controller: ZectranetBundle:Office:addOffice }

zectranet_delete_office:
    pattern: /office/{office_id}/delete
    defaults: { _controller: ZectranetBundle:Office:delete }
    requirements:
        office_id: \d+

zectranet_office_add_post:
    pattern: /office/{office_id}/addNewPost
    defaults: { _controller: ZectranetBundle:OfficePost:addPost }
    requirements:
        office_id: \d+

zectranet_office_get_post:
    pattern: /office/{office_id}/getPosts
    defaults: { _controller: ZectranetBundle:OfficePost:getPosts }
    requirements:
        office_id: \d+

zectranet_show_project:
    pattern: /project/{project_id}
    defaults: { _controller: ZectranetBundle:Project:index }
    requirements:
        project_id: \d+

zectranet_add_project:
    path: /project/add
    defaults: { _controller: ZectranetBundle:Project:addProject }

zectranet_delete_project:
    pattern: /project/{project_id}/delete
    defaults: { _controller: ZectranetBundle:Project:delete }
    requirements:
        project_id: \d+

zectranet_project_add_post:
    pattern: /project/{project_id}/addNewPost
    defaults: { _controller: ZectranetBundle:ProjectPost:addPost }
    requirements:
        project_id: \d+

zectranet_project_get_post:
    pattern: /project/{project_id}/getPosts
    defaults: { _controller: ZectranetBundle:ProjectPost:getPosts }
    requirements:
        project_id: \d+

zectranet_project_add_task:
    pattern: /project/{project_id}/addNewTask
    defaults: { _controller: ZectranetBundle:Project:addTask }
    requirements:
        project_id: \d+

zectranet_project_add_subtask:
    pattern: /project/{project_id}/addNewSubTask
    defaults: { _controller: ZectranetBundle:Project:addSubTask }
    requirements:
        project_id: \d+

zectranet_project_get_tasks:
    pattern: /project/{project_id}/getTasks
    defaults: { _controller: ZectranetBundle:Task:getTasks }
    requirements:
        project_id: \d+

zectranet_project_get_epic_stories:
    pattern: /project/{project_id}/getEpicStories
    defaults: { _controller: ZectranetBundle:Project:getEpicStories }
    requirements:
        project_id: \d+

zectranet_project_add_epic_story:
    pattern: /project/{project_id}/addNewEpicStory
    defaults: { _controller: ZectranetBundle:Project:addNewEpicStory }
    requirements:
        project_id: \d+

zectranet_task_show:
    pattern: /task/{task_id}
    defaults: { _controller: ZectranetBundle:Task:showTask }
    requirements:
        task_id: \d+

zectranet_upload:
    pattern: /upload/
    defaults: { _controller: ZectranetBundle:Upload:index }

zectranet_document_upload:
    pattern: /upload/documents/
    defaults: { _controller: ZectranetBundle:Upload:upload }

zectranet_document_get:
    pattern: /upload/documents/get/
    defaults: { _controller: ZectranetBundle:Upload:getDocuments }

zectranet_document_rename:
    pattern: documents/{fileid}/rename
    defaults: { _controller: ZectranetBundle:Upload:renameDoc }
    requirements:
            fileid: \d+

zectranet_document_delete:
    pattern: documents/{fileid}/delete/
    defaults: { _controller: ZectranetBundle:Upload:removeDoc }
    requirements:
                fileid: \d+

