zectranet_homepage:
    path: /
    defaults: { _controller: ZectranetBundle:Index:index }

zectranet_login:
    path: /login
    defaults: { _controller: ZectranetBundle:Index:login }

zectranet_login_check:
    path: /login_check
    defaults: { _controller: ZectranetBundle:Index:loginCheck }

zectranet_logout:
    path: /logout

zectranet_user_home:
    path: /user/home
    defaults: { _controller: ZectranetBundle:User:home }

zectranet_signup:
    path: /signup
    defaults: { _controller: ZectranetBundle:Index:signup }

zectranet_signup_action:
    path: /signup_action
    defaults: { _controller: ZectranetBundle:Index:signupAct }

zectranet_forgot_password:
    path: /forgot_password
    defaults: { _controller: ZectranetBundle:Index:forgotPassword }

zectranet_reset_password:
    pattern: /reset_password/{keyForAccess}
    defaults: { _controller: ZectranetBundle:Index:resetPassword }

zectranet_reset_password_save:
    pattern: /reset_password_save/{userid}
    defaults: { _controller: ZectranetBundle:Index:resetPasswordSave }

zectranet_wde:
    path: /wde
    defaults: { _controller: ZectranetBundle:User:wde }

zectranet_public_market:
    path: /public_market
    defaults: { _controller: ZectranetBundle:PublicMarket:index }

zectranet_edit_user_page:
    path: /userProfile/edit
    defaults: { _controller: ZectranetBundle:User:editProfilePage }

zectranet_edit_user_page_action:
    path: /userProfile/edit/{user_id}
    defaults: { _controller: ZectranetBundle:User:editProfile }
    requirements:
          user_id: \d+

zectranet_user_page:
    pattern: /userProfile/{user_id}
    defaults: { _controller: ZectranetBundle:User:index, user_id: null }
    requirements:
            user_id: \d+

zectranet_user_settings:
    path: /user/settings
    defaults: { _controller: ZectranetBundle:User:settings }

zectranet_user_settings_general:
    path: /user/settings/general
    defaults: { _controller: ZectranetBundle:User:general }

zectranet_user_settings_email:
    path: /user/settings/email
    defaults: { _controller: ZectranetBundle:User:email }

zectranet_user_settings_site:
    path: /user/settings/site
    defaults: { _controller: ZectranetBundle:User:site }

zectranet_user_settings_changePassword:
    path: /user/settings/change_password
    defaults: { _controller: ZectranetBundle:User:changePassword }

zectranet_generate_avatar:
    path: /user/generate_avatar
    defaults: { _controller: ZectranetBundle:User:generateAvatar }

zectranet_notifications_clear:
    pattern:  /notifications/clear
    defaults: { _controller: ZectranetBundle:Notification:clearNotifications }

zectranet_notifications_show:
    pattern:  /notifications
    defaults: { _controller: ZectranetBundle:Notification:showNotifications }

zectranet_notifications_get:
    pattern:  /notifications/get
    defaults: { _controller: ZectranetBundle:Notification:getNotifications }

zectranet_all_notifications:
    path: user/notifications/all
    defaults: { _controller: ZectranetBundle:Notification:all }

zectranet_delete_all_notifications:
    path: user/notifications/delete_all
    defaults: { _controller: ZectranetBundle:Notification:deleteAll }

zectranet_show_office:
    pattern: /office/{office_id}
    defaults: { _controller: ZectranetBundle:Office:index }
    requirements:
        office_id: \d+

zectranet_add_office:
    path: /office/add
    defaults: { _controller: ZectranetBundle:Office:addOffice }

zectranet_delete_office:
    pattern: /office/{office_id}/delete
    defaults: { _controller: ZectranetBundle:Office:delete }
    requirements:
        office_id: \d+

zectranet_settings_office:
    pattern: /office/{office_id}/settings
    defaults: { _controller: ZectranetBundle:Office:settings }
    requirements:
        office_id: \d+

zectranet_office_get_WDE:
    pattern: /office/{office_id}/getWDE
    defaults: { _controller: ZectranetBundle:Office:getWDE }
    requirements:
        office_id: \d+

zectranet_office_show_WDE:
    pattern: /office/{office_id}/showWDE
    defaults: { _controller: ZectranetBundle:Office:showWDE }
    requirements:
        office_id: \d+

zectranet_get_office_members:
    pattern: /office/{office_id}/getMembers
    defaults: { _controller: ZectranetBundle:Office:getMembers }
    requirements:
        office_id: \d+

zectranet_save_office_members:
    pattern: /office/{office_id}/saveMembersState
    defaults: { _controller: ZectranetBundle:Office:saveMembers }
    requirements:
        office_id: \d+

zectranet_office_change_visible_state:
    pattern: /office/{office_id}/settings/visibleStateChange
    defaults: { _controller: ZectranetBundle:Office:visibleStateChange }
    requirements:
        office_id: \d+

zectranet_office_add_post:
    pattern: /office/{office_id}/addNewPost
    defaults: { _controller: ZectranetBundle:OfficePost:addPost }
    requirements:
        office_id: \d+

zectranet_office_get_post:
    pattern: /office/{office_id}/getPosts
    defaults: { _controller: ZectranetBundle:OfficePost:getPosts }
    requirements:
        office_id: \d+

zectranet_show_project:
    pattern: /project/{project_id}
    defaults: { _controller: ZectranetBundle:Project:index }
    requirements:
        project_id: \d+

zectranet_settings_project:
    pattern: /project/{project_id}/settings
    defaults: { _controller: ZectranetBundle:Project:settings }
    requirements:
        project_id: \d+

zectranet_project_change_visible_state:
    pattern: /project/{project_id}/settings/visibleStateChange
    defaults: { _controller: ZectranetBundle:Project:visibleStateChange }
    requirements:
        project_id: \d+

zectranet_get_project_members:
    pattern: /project/{project_id}/getMembers
    defaults: { _controller: ZectranetBundle:Project:getMembers }
    requirements:
        project_id: \d+

zectranet_get_project_versions:
    pattern: /project/{project_id}/getVersions
    defaults: { _controller: ZectranetBundle:Project:getProjectVersions }
    requirements:
        project_id: \d+

zectranet_add_project_version:
    pattern: /project/{project_id}/addNewVersion
    defaults: { _controller: ZectranetBundle:Project:addNewProjectVersion }
    requirements:
        project_id: \d+

zectranet_save_project_members:
    pattern: /project/{project_id}/saveMembersState
    defaults: { _controller: ZectranetBundle:Project:saveMembers }
    requirements:
        project_id: \d+

zectranet_accept_request_user_office:
    pattern: /office/{office_id}/acceptRequestUserOffice
    defaults: { _controller: ZectranetBundle:Office:acceptRequestUserOffice }
    requirements:
        office_id: \d+

zectranet_accept_request_user_project:
    pattern: /project/{project_id}/acceptRequestUserProject
    defaults: { _controller: ZectranetBundle:Project:acceptRequestUserProject }
    requirements:
        project_id: \d+

zectranet_accept_request_project:
    pattern: /project/{project_id}/{office_id}/acceptRequestOfficeProject
    defaults: { _controller: ZectranetBundle:Project:acceptRequestOfficeProject }
    requirements:
        project_id: \d+
        office_id: \d+

zectranet_decline_request_user_office:
    pattern: /office/{office_id}/declineRequestUserOffice
    defaults: { _controller: ZectranetBundle:Office:declineRequestUserOffice }
    requirements:
        office_id: \d+

zectranet_decline_request_user_project:
    pattern: /project/{project_id}/declineRequestUserProject
    defaults: { _controller: ZectranetBundle:Project:declineRequestUserProject }
    requirements:
        project_id: \d+

zectranet_decline_request_project:
    pattern: /project/{project_id}/declineRequestOfficeProject
    defaults: { _controller: ZectranetBundle:Project:declineRequestOfficeProject }
    requirements:
        project_id: \d+

zectranet_get_project_offices:
    pattern: /project/{project_id}/getOffices
    defaults: { _controller: ZectranetBundle:Project:getOffices }
    requirements:
        project_id: \d+

zectranet_project_add_offices:
    pattern: /project/{project_id}/addOffices
    defaults: { _controller: ZectranetBundle:Project:addOffices }
    requirements:
        project_id: \d+

zectranet_project_remove_offices:
    pattern: /project/{project_id}/removeOffices
    defaults: { _controller: ZectranetBundle:Project:removeOffices }
    requirements:
        project_id: \d+

zectranet_add_project:
    path: /project/add
    defaults: { _controller: ZectranetBundle:Project:addProject }

zectranet_delete_project:
    pattern: /project/{project_id}/delete
    defaults: { _controller: ZectranetBundle:Project:delete }
    requirements:
        project_id: \d+

zectranet_project_add_post:
    pattern: /project/{project_id}/addNewPost
    defaults: { _controller: ZectranetBundle:ProjectPost:addPost }
    requirements:
        project_id: \d+

zectranet_project_get_post:
    pattern: /project/{project_id}/getPosts
    defaults: { _controller: ZectranetBundle:ProjectPost:getPosts }
    requirements:
        project_id: \d+

zectranet_subtask_make_task:
    pattern: /subtask/{task_id}/makeTask
    defaults: { _controller: ZectranetBundle:Task:makeSubtaskTask }

zectranet_project_add_task:
    pattern: /project/{project_id}/addNewTask
    defaults: { _controller: ZectranetBundle:Project:addTask }
    requirements:
        project_id: \d+

zectranet_project_add_subtask:
    pattern: /project/{project_id}/addNewSubTask
    defaults: { _controller: ZectranetBundle:Project:addSubTask }
    requirements:
        project_id: \d+

zectranet_project_get_tasks:
    pattern: /project/{project_id}/getTasks
    defaults: { _controller: ZectranetBundle:Task:getTasks }
    requirements:
        project_id: \d+

zectranet_project_get_epic_stories:
    pattern: /project/{project_id}/getEpicStories
    defaults: { _controller: ZectranetBundle:Project:getEpicStories }
    requirements:
        project_id: \d+

zectranet_project_add_epic_story:
    pattern: /project/{project_id}/addNewEpicStory
    defaults: { _controller: ZectranetBundle:Project:addNewEpicStory }
    requirements:
        project_id: \d+

zectranet_project_delete_epic_stories:
    pattern: /project/{project_id}/deleteEpicStories
    defaults: { _controller: ZectranetBundle:Project:deleteEpicStories }
    requirements:
        project_id: \d+

zectranet_task_show:
    pattern: /task/{task_id}
    defaults: { _controller: ZectranetBundle:Task:showTask }
    requirements:
        task_id: \d+

zectranent_task_get_single:
    pattern: /task/get/{task_id}
    defaults: { _controller: ZectranetBundle:Task:getSingleTask }
    requirements:
        task_id: \d+

zectranet_task_edit_info:
    pattern: /task/{task_id}/edit_info
    defaults: { _controller: ZectranetBundle:Task:editInfo }
    requirements:
        task_id: \d+

zectranet_task_edit_descritpion:
    pattern: /task/{task_id}/edit_description
    defaults: { _controller: ZectranetBundle:Task:editDescription }
    requirements:
        task_id: \d+

zectranet_task_delete:
    pattern: /task/{task_id}/deleteTask
    defaults: { _controller: ZectranetBundle:Task:deleteTask }
    requirements:
        task_id: \d+

zectranet_upload:
    pattern: /upload/
    defaults: { _controller: ZectranetBundle:Upload:index }

zectranet_document_upload:
    pattern: /upload/documents/
    defaults: { _controller: ZectranetBundle:Upload:upload }

zectranet_document_get:
    pattern: /upload/documents/get/
    defaults: { _controller: ZectranetBundle:Upload:getDocuments }

zectranet_document_rename:
    pattern: /documents/{fileid}/rename
    defaults: { _controller: ZectranetBundle:Upload:renameDoc }
    requirements:
        fileid: \d+

zectranet_document_delete:
    pattern: /documents/{fileid}/delete/
    defaults: { _controller: ZectranetBundle:Upload:removeDoc }
    requirements:
        fileid: \d+

zectranet_show_sprint:
    pattern: /office/{office_id}/sprint/{sprint_id}
    defaults: { _controller: ZectranetBundle:Sprint:index }
    requirements:
        office_id: \d+
        sprint_id: \d+

zectranet_sprint_add:
    pattern: /sprint/{office_id}/addSprint
    defaults: { _controller: ZectranetBundle:Sprint:addSprint }
    requirements:
        office_id: \d+

zectranet_sprint_delete:
    pattern: /sprint/{office_id}/delete/{sprint_id}
    defaults: { _controller: ZectranetBundle:Sprint:deleteSprint }
    requirements:
        office_id: \d+
        sprint_id: \d+

zectranet_sprint_add_tasks:
    pattern: /sprint/{sprint_id}/addTasksToSprint
    defaults: { _controller: ZectranetBundle:Sprint:addTasksToSprint }
    requirements:
        sprint_id: \d+

zectranet_detach_task_from_sprint:
    pattern: /task/detach_from_sprint/{task_id}
    defaults: { _controller: ZectranetBundle:Task:detachFromSprint }
    requirements:
        task_id: \d+

zectranet_sprint_get_tasks:
    pattern: /sprint/{sprint_id}/getTasks
    defaults: { _controller: ZectranetBundle:Sprint:getTasks }
    requirements:
        sprint_id: \d+

zectranet_sprint_change_state:
    pattern: /sprint/{sprint_id}/changeState/{state}
    defaults: { _controller: ZectranetBundle:Sprint:changeSprintState }
    requirements:
        sprint_id: \d+
        state: \d+

zectranet_InsertScreenshotsInPHP:
    pattern: /upload/insertscreenshots
    defaults: { _controller: ZectranetBundle:Upload:Insert_Screenshots_InPHP }

zectranet_task_get_post:
    pattern: /task/{task_id}/getPosts
    defaults: { _controller: ZectranetBundle:Task:getPosts }
    requirements:
        office_id: \d+

zectranet_task_add_post:
    pattern: /task/{task_id}/addPosts
    defaults: { _controller: ZectranetBundle:Task:addPost }
    requirements:
        office_id: \d+

zectranet_show_project_versions:
    pattern: /project/{project_id}/showVersions
    defaults: { _controller: ZectranetBundle:Project:showProjectVersion }
    requirements:
        project_id: \d+
