parameters:
#    parameter_name: value

services:
    service_name:
        class: ZectranetBundle\Services\TaskLogger
        arguments: [@security.token_storage, @doctrine.orm.default_entity_manager]

    zectranet.notifier:
        class: ZectranetBundle\Services\Notifier
        arguments: [@security.token_storage, @doctrine.orm.entity_manager, @router, @mailer]