parameters:
#    parameter_name: value

services:
    zectranet.taskLogger:
        class: ZectranetBundle\Services\TaskLogger
        arguments: [@security.token_storage, @doctrine.orm.default_entity_manager]

    zectranet.notifier:
        class: ZectranetBundle\Services\Notifier
        arguments: [@security.token_storage, @doctrine.orm.entity_manager, @router, @mailer]

    zectranet.errorLogger:
        class: ZectranetBundle\Services\ErrorLogger
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]

    zectranet.projectLogger:
        class: ZectranetBundle\Services\ProjectLogger
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]

    zectranet.officeArchiveLogger:
        class: ZectranetBundle\Services\OfficeArchiveLogger
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]